project(
  'selecppion',
  'cpp',
  version: '0.2.0',
  default_options: ['cpp_std=c++23', 'buildtype=release']
)

# Define custom warning or optimization flags
extra_flags_gcc_clang = [
  #'-march=native',
  '-flto',

  #'-Werror',
  '-Wall',
  '-Wextra',
  '-Wpedantic',
  '-Wdouble-promotion',
  '-Wformat=2',
  '-Wundef',
  '-Wcast-qual',
  '-Woverloaded-virtual',
  '-Wuninitialized',
  '-Winit-self',
  '-Wredundant-decls',
  '-Wsuggest-override',
  '-Wshadow',
  '-Wnon-virtual-dtor',
  #'-Wold-style-cast',
  '-Wcast-align',
  '-Wunused',
  '-Wconversion',
  #'-Wsign-conversion',

  '-Wextra-semi',
  '-Wctor-dtor-privacy',
  '-Wzero-as-null-pointer-constant',
  '-Wlogical-op',
  #'-Wfloat-equal',
  '-Wpessimizing-move',
  '-Wredundant-move'
]

extra_flags_gcc = [
  '-Ofast',
  '-Walloca',
  '-Wcast-align=strict',
  '-Wimplicit-fallthrough=5',
  '-Wduplicated-cond',
  '-Wduplicated-branches',
  # '-Wuseless-cast',
  '-Wtrampolines'
]

extra_flags_clang = [
  '-O3',
  '-ffast-math',
  '-Wimplicit-fallthrough',
  '-Wshadow-field',
  '-Wabstract-final-class',
  '-Wheader-hygiene'
]

extra_flags_msvc = [
  '/Wall',
  '/W4',
  '/w14242',
  '/w14265',
  '/w14287',
  '/we4289',
  '/w14296',
  '/w14311',
  '/utf-8'
]

# Safely check which flags are supported by the active compiler
cpp_compiler = meson.get_compiler('cpp')

if cpp_compiler.get_id() == 'gcc'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_gcc_clang + extra_flags_gcc)
elif cpp_compiler.get_id() == 'clang'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_gcc_clang + extra_flags_clang)
elif cpp_compiler.get_id() == 'msvc'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_msvc)
endif

# Only apply flags to current project
add_project_arguments(supported_flags_lib, language: 'cpp')

# Point the include directory to 'src'
inc_dir = include_directories('src')

# Source files
sources = files(
  'src/secpion/se_config.cpp',
  'src/secpion/se_individual.cpp'
)

# External dependencies:

# Import the CMake module
cmake = import('cmake')

# Configure taocpp-json as a CMake subproject
tao_json_sub = cmake.subproject('taocpp-json')
# Get the dependency target generated by CMake
tao_json_dep = tao_json_sub.dependency('taocpp-json', include_type: 'system')

# Main dependencies:
argparse_dep = dependency(
  'argparse',
  fallback: ['argparse', 'argparse_dep']
)

spdlog_dep = dependency(
  'spdlog',
  fallback: ['spdlog', 'spdlog_dep'],
  include_type: 'system'
)

fmt_dep = dependency(
  'fmt',
  fallback: ['fmt', 'fmt_dep']
)

node_crunch2_dep = dependency(
  'node_crunch2',
  fallback: ['node_crunch2', 'node_crunch2_dep']
)

# For unit testing:
snitch_dep = dependency(
  'snitch',
  fallback: ['snitch', 'snitch_dep'],
)

# Build the library
selecppion_lib = shared_library(
  'selecppion',
  sources,
  include_directories: inc_dir,
  dependencies: [tao_json_dep, spdlog_dep, fmt_dep, node_crunch2_dep],
  install: true
)

# Declare dependency for other targets/projects
selecppion_dep = declare_dependency(
  include_directories: inc_dir,
  link_with: selecppion_lib,
  dependencies: [tao_json_dep, spdlog_dep, fmt_dep, node_crunch2_dep]
)

# Register the dependency
meson.override_dependency('selecppion', selecppion_dep)

# Explicitly list header files to install them to system paths
install_headers(
  'src/secpion/se_config.hpp',
  'src/secpion/se_exceptions.hpp',
  'src/secpion/se_individual.hpp',
  'src/secpion/se_population.hpp',
  'src/secpion/se_population_node1.hpp',
  'src/secpion/se_population_node2.hpp',
  'src/secpion/se_population_node3.hpp',
  'src/secpion/se_population_node4.hpp',
  'src/secpion/se_population_node5.hpp',
  'src/secpion/se_population_node6.hpp',
  'src/secpion/se_population_node7.hpp',
  'src/secpion/se_population_node8.hpp',
  'src/secpion/se_population_node9.hpp',
  'src/secpion/se_population_node10.hpp',
  'src/secpion/se_population_node11.hpp',
  'src/secpion/se_population_selector.hpp',
  'src/secpion/se_random.hpp',
  'src/secpion/se_server.hpp',
  'src/secpion/se_utils.hpp',
  subdir: 'secpion'
)

# Unit test configuration
test_sources = files(
  'tests/test_all.cpp',
  'tests/test_config.cpp',
  'tests/test_individual.cpp',
  'tests/test_population.cpp',
  'tests/test_population_node1.cpp',
  'tests/test_population_node2.cpp',
  'tests/test_population_node3.cpp',
  'tests/test_population_node4.cpp',
  'tests/test_population_node5.cpp',
  'tests/test_population_node6.cpp',
  'tests/test_population_node7.cpp',
  'tests/test_population_node8.cpp',
  'tests/test_population_node9.cpp',
  'tests/test_population_node10.cpp',
  'tests/test_population_node11.cpp',
  'tests/test_random_generator.cpp',
  'tests/test_server.cpp'
)

test_exe = executable(
  'selecppion_tests', test_sources, dependencies: [selecppion_dep, snitch_dep]
)

test('all unit tests', test_exe)

executable(
  'bin_packing_example', files('examples/bin_packing/src/main.cpp'),
  include_directories: include_directories('examples/bin_packing/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)

executable(
  'rastrigin_example', files('examples/function_optimization/rastrigin/src/main.cpp'),
  include_directories: include_directories('examples/function_optimization/rastrigin/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)

executable(
  'rosenbrock_example', files('examples/function_optimization/rosenbrock/src/main.cpp'),
  include_directories: include_directories('examples/function_optimization/rosenbrock/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)

executable(
  'knapsack_example', files('examples/knapsack/src/main.cpp'),
  include_directories: include_directories('examples/knapsack/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)

executable(
  'neural_net1_example', files('examples/neural_net1/src/main.cpp'),
  include_directories: include_directories('examples/neural_net1/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)

executable(
  'queens_example', files('examples/queens/src/main.cpp'),
  include_directories: include_directories('examples/queens/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)

executable(
  'sudoku1_example', files('examples/sudoku1/src/main.cpp'),
  include_directories: include_directories('examples/sudoku1/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)

executable(
  'sudoku2_example', files('examples/sudoku2/src/main.cpp'),
  include_directories: include_directories('examples/sudoku2/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)

executable(
  'tsp_example', files('examples/tsp/src/main.cpp'),
  include_directories: include_directories('examples/tsp/src', 'examples/utils'),
   dependencies: [selecppion_dep, argparse_dep]
)
